# Generated by Django 4.2.3 on 2023-07-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nome_produto', models.CharField(max_length=100)),
                ('marca_produto', models.CharField(max_length=50)),
                ('pet_produto', models.CharField(max_length=100)),
                ('tipo_produto', models.CharField(max_length=100)),
                ('preço_produto', models.FloatField()),
                ('apresentacao_produto', models.CharField(max_length=100)),
            ],
        ),
    ]
