# Generated by Django 4.2.3 on 2023-07-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preço_produto',
            new_name='preco_produto',
        ),
    ]
